name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check format (prettier)
        run: npm run format-check

      - name: Lint (eslint)
        run: npm run lint-check

      - name: Typescript Compile
        run: npm run tsc

      - name: Compile
        run: npm run build
